#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate --noinput
python manage.py collectstatic --noinput
# python manage.py runserver 0.0.0.0:8000
gunicorn wagtail_portfolio_blog.wsgi:application -b unix:/run/gunicorn/gunicorn.sock
