# This is a basic workflow to help you get started with Actions

name: Deploy to EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: mkdir -p /home/ubuntu/srv
      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/srv/
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}
      - name: create env file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          run: |
            touch /home/ubuntu/srv/.env
            echo "${{ secrets.DJANGO_SETTINGS_MODULE }}" >> /home/ubuntu/srv/.env
            echo "${{ secrets.SECRET_KEY }}" >> /home/ubuntu/srv/.env
            echo "${{ secrets.SQL_ENGINE }}" >> /home/ubuntu/srv/.env
            echo "${{ secrets.SQL_DATABASE }}" >> /home/ubuntu/srv/.env
            echo "${{ secrets.SQL_USER }}" >> /home/ubuntu/srv/.env
            echo "${{ secrets.SQL_PASSWORD }}" >> /home/ubuntu/srv/.env
            echo "${{ secrets.SQL_HOST }}" >> /home/ubuntu/srv/.env
            echo "${{ secrets.SQL_PORT }}" >> /home/ubuntu/srv/.env
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            ****sh /home/ubuntu/srv/compose/deploy.sh
